<a href="https://colab.research.google.com/github/JagdishMane/numpy-pytorch-tensorflow/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


- numpy = Numerical Python
- Library used to wrok with arrays
- numpy are 50x  faster than python list []
- Written in Python + C++

In [4]:
print(np.__version__)

2.0.2


In [5]:
# ndarray is array object
# Create it using array()

arr = np.array([1, 2, 3])
print(arr)


[1 2 3]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


## 0-D Array

In [15]:
a = np.array(42)
print(a)

42


## 1-D Array

In [16]:
b = np.array([1, 2, 3, 4])
print(b)

[1 2 3 4]


## 2-D Array

In [17]:
c = np.array([[1, 2], [4, 5]])
print(c)

[[1 2]
 [4 5]]


## 3-D Array

In [18]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [0, 1, 2]]])
print(d)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]


## Check Dimension

In [22]:
print(a.ndim, b.ndim, c.ndim, d.ndim)

0 1 2 3
