<a href="https://colab.research.google.com/github/JagdishMane/numpy-pytorch-tensorflow/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


- numpy = Numerical Python
- Library used to wrok with arrays
- numpy are 50x  faster than python list []
- Written in Python + C++

In [4]:
print(np.__version__)

2.0.2


In [5]:
# ndarray is array object
# Create it using array()

arr = np.array([1, 2, 3])
print(arr)


[1 2 3]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


## 0-D Array

In [15]:
a = np.array(42)
print(a)

42


## 1-D Array

In [16]:
b = np.array([1, 2, 3, 4])
print(b)

[1 2 3 4]


## 2-D Array

In [17]:
c = np.array([[1, 2], [4, 5]])
print(c)

[[1 2]
 [4 5]]


## 3-D Array

In [18]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [0, 1, 2]]])
print(d)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]


## Check Dimension

In [22]:
print(a.ndim, b.ndim, c.ndim, d.ndim)

0 1 2 3


## Higher Dimensional Arrays

In [26]:
ndmin_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], ndmin=3)
print(ndmin_arr)
print(ndmin_arr.ndim)

[[[1 2 3 4]
  [5 6 7 8]]]
3


## Numpy Array Indexing

In [28]:
arr = np.array([1, 3, 4])
print(arr[0])
print(arr[1])
print(arr[2])

1
3
4


In [32]:
arr = np.array([1, 2, 3, 4])
print("arr[0] + arr[1] = " ,arr[0] + arr[1])

arr[0] + arr[1] =  3


In [36]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,0]])
print("4th element of 1st row: ", arr[0, 3])
print("3rd element of 2nd row: ", arr[1, 2])

4th element of 1st row:  4
3rd element of 2nd row:  8


In [46]:
arr = np.array([[[1, 2, 3], [4,5,6], [0,0,0]],[[7,8,9], [0,1,2], [0,0,0]],[[3,4,5], [6,7,8], [0,0,0]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [0 0 0]]

 [[7 8 9]
  [0 1 2]
  [0 0 0]]

 [[3 4 5]
  [6 7 8]
  [0 0 0]]]


In [51]:
print(arr[2, 1, 2])
print(arr[1, 2, 1])
print(arr[0, 1, 2])

8
0
6


## Negative Indexing

In [58]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr)
print(arr[1,1])
print(arr[1, -1])
print(arr[1, -2])
print(arr[0, -2])


[[1 2 3 4 5]
 [6 7 8 9 0]]
7
0
9
4


In [61]:
arr = np.array([[[1,2], [3,4]],[[5,6], [7,8]]])
print(arr)
print(arr[1,1,0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
7


## Array Slicing

In [77]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:6])
print(arr[1:])
print(arr[:-1])
print(arr[1:6:2])
print(arr[:4])
print(arr[-4:-1])
print(arr[-5:-2])


[2 3 4 5 6]
[2 3 4 5 6 7]
[1 2 3 4 5 6]
[2 4 6]
[1 2 3 4]
[4 5 6]
[3 4 5]


## STEP

In [78]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:6:2])
print(arr[::2])

[2 4 6]
[1 3 5 7]


In [87]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,0]])
print(arr[1, 1:4])
print(arr[0, 1:4])
print(arr[0:2, 1])  ## From both elements print index 1
print(arr[0:2, 1:2])  ## From both elements print index 1 in 2-D Array

[7 8 9]
[2 3 4]
[2 7]
[[2]
 [7]]


In [88]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:2])

[1 2]


## Data Types in Numpy

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

In [91]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr.dtype)
arrstr = np.array(["apple", "banana", "cherry"])
print(arrstr.dtype)

int64
<U6


In [95]:
## Creating an array with defined datatypes
arr_s = np.array([1, 2, 3], dtype='S')
print(arr_s)
print(arr_s.dtype)
## b'1' ===> Bytes literal = data stored in bytes.
## S1 ===> Byte String

[b'1' b'2' b'3']
|S1


In [96]:
arr_u = np.array([1, 2, 3], dtype='U')
print(arr_u)
print(arr_u.dtype)

## U ==> unicode string

['1' '2' '3']
<U1


In [99]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [106]:
### Convert dtypes
arr = np.array([1.1, 2.1, 3.1])
print(arr)
print(arr.dtype)

newarr = arr.astype('i') ### To integer
print(newarr)
print(newarr.dtype)

barr = arr.astype(bool)
print(barr)
print(barr.dtype)

new = np.array([-1, 0, 1])
newarr = new.astype(bool)
print(newarr)
print(newarr.dtype)

new = np.array([0, 0, 1])
newarr = new.astype(bool)
print(newarr)
print(newarr.dtype)

[1.1 2.1 3.1]
float64
[1 2 3]
int32
[ True  True  True]
bool
[ True False  True]
bool
[False False  True]
bool


### Create Array COPY

In [112]:
arr = np.array([1,2,3])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)
print(x[0])

[42  2  3]
[1 2 3]
1


## Create VIEW

In [114]:
### View refrences to the orginial array , Hence change in orignail array is displayed in view as well.
v = arr.view()
arr[0] = 43
print(arr)
print(v)
print(v[0])


[43  2  3]
[43  2  3]
43


In [117]:
## Original array gets changed when view is changed.
arr = np.array([1, 2, 3])
x = arr.view()
x[0] = 31
print(arr)
print(x)

[31  2  3]
[31  2  3]


In [120]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

### COPY retruns NONE, ie COPY OWNS the data
### View retruns original array, View does not own data it refers to original object

None
[1 2 3 4 5]


### SHAPE of an array

In [130]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.shape)
print("Two Dimensions : First dimension has 4 elemeber and second dimension has 4")

print("\n","Creating an array with 5 dimensionsons using ndmin")
arr = np.array([1, 2, 3, 4, 5], ndmin=5)
print("\n" ,arr)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
Two Dimensions : First dimension has 4 elemeber and second dimension has 4

 Creating an array with 5 dimensionsons using ndmin

 [[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


### RESHAPE

In [131]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)  # 4 arrys with 3 elements
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [133]:
newarr = arr.reshape(3, 2, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [136]:
newarr = arr.reshape(3, 4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Iterating

In [137]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [138]:
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [139]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


## Split

In [141]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
print(newarr)

newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [142]:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]
