<a href="https://colab.research.google.com/github/JagdishMane/numpy-pytorch-tensorflow/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


- numpy = Numerical Python
- Library used to wrok with arrays
- numpy are 50x  faster than python list []
- Written in Python + C++

In [4]:
print(np.__version__)

2.0.2


In [5]:
# ndarray is array object
# Create it using array()

arr = np.array([1, 2, 3])
print(arr)


[1 2 3]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


## 0-D Array

In [15]:
a = np.array(42)
print(a)

42


## 1-D Array

In [16]:
b = np.array([1, 2, 3, 4])
print(b)

[1 2 3 4]


## 2-D Array

In [17]:
c = np.array([[1, 2], [4, 5]])
print(c)

[[1 2]
 [4 5]]


## 3-D Array

In [18]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [0, 1, 2]]])
print(d)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]


## Check Dimension

In [22]:
print(a.ndim, b.ndim, c.ndim, d.ndim)

0 1 2 3


## Higher Dimensional Arrays

In [26]:
ndmin_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], ndmin=3)
print(ndmin_arr)
print(ndmin_arr.ndim)

[[[1 2 3 4]
  [5 6 7 8]]]
3


## Numpy Array Indexing

In [28]:
arr = np.array([1, 3, 4])
print(arr[0])
print(arr[1])
print(arr[2])

1
3
4


In [32]:
arr = np.array([1, 2, 3, 4])
print("arr[0] + arr[1] = " ,arr[0] + arr[1])

arr[0] + arr[1] =  3


In [36]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,0]])
print("4th element of 1st row: ", arr[0, 3])
print("3rd element of 2nd row: ", arr[1, 2])

4th element of 1st row:  4
3rd element of 2nd row:  8


In [46]:
arr = np.array([[[1, 2, 3], [4,5,6], [0,0,0]],[[7,8,9], [0,1,2], [0,0,0]],[[3,4,5], [6,7,8], [0,0,0]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [0 0 0]]

 [[7 8 9]
  [0 1 2]
  [0 0 0]]

 [[3 4 5]
  [6 7 8]
  [0 0 0]]]


In [51]:
print(arr[2, 1, 2])
print(arr[1, 2, 1])
print(arr[0, 1, 2])

8
0
6


## Negative Indexing

In [58]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr)
print(arr[1,1])
print(arr[1, -1])
print(arr[1, -2])
print(arr[0, -2])


[[1 2 3 4 5]
 [6 7 8 9 0]]
7
0
9
4


In [61]:
arr = np.array([[[1,2], [3,4]],[[5,6], [7,8]]])
print(arr)
print(arr[1,1,0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
7


## Array Slicing

In [77]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:6])
print(arr[1:])
print(arr[:-1])
print(arr[1:6:2])
print(arr[:4])
print(arr[-4:-1])
print(arr[-5:-2])


[2 3 4 5 6]
[2 3 4 5 6 7]
[1 2 3 4 5 6]
[2 4 6]
[1 2 3 4]
[4 5 6]
[3 4 5]


## STEP